### PR TITLE
reexport types

### PR DESCRIPTION
**Pull request by inoas**

### CODE REVIEW

**Comment by inoas** [comment]
@jly36963 is this better?

I am considering just putting all the type reexports into a single types module though... might be easier also less duplication.

**Comment by jly36963** [comment]
This solution solves my problem from [here](https://github.com/inoas/gleam-cake/issues/1#issuecomment-2223781385)

It also solves another issue:
- I go to the hex docs to find function I need
- I don't know a given function is what I need, as the input or return type is private
- I start digging around in the github repo to get this confirmation (or dig deeper)
- This is what got me looking in the `internal` directory in the first place.

With these types exposed (re-exported), I can now find everything I need in a given module. I really like this.

**Comment by inoas** [comment]
@jly36963 however, instead of doing it per module I consider adding a non-internal types module and put all of them there. I am not sure if DX would be better or worse doing so.

**Comment by inoas** [comment]
I have asked about this on gleam discord, maybe some ideas come up there https://discord.com/channels/768594524158427167/1261064495233630351

**Comment by jly36963** [comment]
Wherever pragmatic, I do like locality-of-behavior -- if the functions and types are colocated, the reasoning is easier to follow.

**Comment by inoas** [comment]
> Wherever pragmatic, I do like locality-of-behavior -- if the functions and types are colocated, the reasoning is easier to follow.

If it is beneficial to the developer then it is worth the hassle.

**Comment by inoas** [comment]
> I have asked about this on gleam discord, maybe some ideas come up there https://discord.com/channels/768594524158427167/1261064495233630351

no more feedback over there (sadly) so I have merged this and releasing now.

**Comment by jly36963** [comment]
Sweet, I'm completely off of internals

**Pull request merged**
